#!/bin/bash

HOST=$(hostname)

for f in /tmp/dse-graph-loader-*; do
    [ -e "$f" ] && echo "graph loader found" || (echo "dse-graph-loader not found in the /tmp directory. Exiting"; exit;)
    break
done

if [ "$HOST" == "node0" ]
then
    echo "Using node0 for address"
    java -Xms4096M -Xmx4096M -cp /tmp/dse-graph-loader-*/dse-graph-loader-*-uberjar.jar com.datastax.dsegraphloader.cli.Executable -graph northwind -address node0 northwind-mapping.groovy
else
    echo "Using localhost for address"
    java -Xms4096M -Xmx4096M -cp /tmp/dse-graph-loader-*/dse-graph-loader-*-uberjar.jar com.datastax.dsegraphloader.cli.Executable -graph northwind -address localhost northwind-mapping.groovy
fi
